#4612-app solve wrong-import bug
thx @teosarca for the pointer
sometimes report service throws NoClassDefFoundError: org/apache/activemq/util/ByteArrayInputStream

(cherry picked from commit cd6415054bf3c1dd5d2806c1272ac14729ca983f)