Avoid using Postgres OID (#10208)
* fix QuerySelectionToDeleteHelper

stack trace was:

org.adempiere.exceptions.DBException: ERROR: column "oid" does not exist
  Position: 259
Additional parameters:
 I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1000941, trxName=null]
 IQueueProcessor: ThreadPoolQueueProcessor{name=FactAcctLogWorkpackageProcessor, executor=BlockingExecutorWrapper(semaphore=java.util.concurrent.Semaphore@33050aae[Permits = 0], delegate=java.util.concurrent.ThreadPoolExecutor@4c5ed220[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 46], logger=Logger[org.adempiere.util.concurrent.BlockingExecutorWrapper])}
 trxName: <<ThreadInherited>>
	SQL: UPDATE Fact_Acct_Log t
 SET ProcessingTag=?
 FROM (
 SELECT Action,AD_Client_ID,AD_Org_ID,AmtAcctCr,AmtAcctDr,C_AcctSchema_ID,C_ElementValue_ID,C_Period_ID,Created,CreatedBy,DateAcct,Fact_Acct_ID,IsActive,PostingType,ProcessingTag,Qty,Updated,UpdatedBy
 , oid as ZZ_RowId  FROM Fact_Acct_Log
 WHERE ((ProcessingTag IS NULL))
 LIMIT 500  OFFSET 0) f
 WHERE t.oid = f.ZZ_RowId
	SQL params: [6ac227c0-6225-4199-84b3-ec93158253de]
	at org.adempiere.exceptions.DBException.wrapIfNeeded(DBException.java:92)
	at org.compiere.util.DB.executeUpdate(DB.java:948)
	at org.compiere.util.DB.executeUpdateEx(DB.java:994)
	at org.compiere.util.DB.executeUpdateEx(DB.java:979)
	at org.adempiere.ad.dao.impl.TypedSqlQuery.updateSql_UsingSelectFromSubQuery(TypedSqlQuery.java:1853)
	at org.adempiere.ad.dao.impl.TypedSqlQuery.updateSql(TypedSqlQuery.java:1777)
	at org.adempiere.ad.dao.impl.TypedSqlQuery.updateDirectly(TypedSqlQuery.java:1733)
	at org.adempiere.ad.dao.impl.CompositeQueryUpdaterExecutor.execute(CompositeQueryUpdaterExecutor.java:51)
	at de.metas.acct.aggregation.impl.FactAcctLogDAO.updateProcessingTag(FactAcctLogDAO.java:87)
	at de.metas.acct.aggregation.impl.FactAcctLogDAO.tagAndRetrieve(FactAcctLogDAO.java:68)
	at de.metas.acct.aggregation.impl.FactAcctLogBL$1.run(FactAcctLogBL.java:65)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:147)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:137)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:753)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:666)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:567)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:498)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.callInNewTrx(AbstractTrxManager.java:476)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.runInNewTrx(AbstractTrxManager.java:470)
	at de.metas.acct.aggregation.impl.FactAcctLogBL.processAll(FactAcctLogBL.java:59)
	at de.metas.acct.aggregation.async.FactAcctLogWorkpackageProcessor.processWorkPackage(FactAcctLogWorkpackageProcessor.java:69)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:336)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:328)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.lambda$run0$1(WorkpackageProcessorTask.java:199)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:105)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:95)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:753)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:666)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:574)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run0(WorkpackageProcessorTask.java:193)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.lambda$run$0(WorkpackageProcessorTask.java:158)
	at de.metas.monitoring.adapter.PerformanceMonitoringService.lambda$monitorTransaction$1(PerformanceMonitoringService.java:83)
	at de.metas.monitoring.adapter.apm.APMPerformanceMonitoringService.monitorTransaction(APMPerformanceMonitoringService.java:64)
	at de.metas.monitoring.adapter.PerformanceMonitoringService.monitorTransaction(PerformanceMonitoringService.java:81)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:157)
	at org.adempiere.util.concurrent.BlockingExecutorWrapper$1.run(BlockingExecutorWrapper.java:90)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: ERROR: column "oid" does not exist
  Position: 259
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2505)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2241)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:447)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:368)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:158)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:1502)
	at org.adempiere.sql.impl.CPreparedStatementProxy.executeUpdate(CPreparedStatementProxy.java:138)
	at org.compiere.util.DB.executeUpdate(DB.java:879)
	... 37 common frames omitted

* get rid of AdempiereDatabase.getRowIdSql() because we no longer support OIDs

Currently it was used to UPDATE directly following tables
* T_Query_Selection_ToDelete - which i've fixed in previous commit
* C_SubscriptionProgress
* PP_MRP
* C_Invoice_Line_Alloc
* C_Invoice_Candidate
* M_ReceiptSchedule
* M_ShipmentSchedule

all of those tables have sigle primary key

* add Fact_Fact_Log.Fact_Fact_Log_ID