Fix Lagerwert(Excel) report (#19844)
* Fix Lagerwert(Excel) report

* ignore failing test

thrown error:
org.adempiere.exceptions.AdempiereException: Enddatum 31.12.2025 der letzten Periode des Kalenders BuchfĂźhrungs-Kalender liegt vor dem Enddatum der Vertragsperiode.

	at de.metas.contracts.interceptor.C_Flatrate_Term.validatePeriods(C_Flatrate_Term.java:269)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

(cherry picked from commit 9ddc798bcb4707e7bd5451d999bcc5c964ba2824)

# Conflicts:
#	backend/de.metas.acct.base/src/main/sql/postgresql/ddl/views/M_CostDetail_v.sql