hotfixing failing migration script
ERROR:  cannot drop table m_receiptschedule column ishuprepared because
other objects depend on it

https://github.com/metasfresh/metasfresh/issues/3086