Column R_Request was removed sometime ago. Now also adapting model classes (#17688) (#17705)
* Column R_Request was removed sometime ago. Now also adapting model classes
* Trace.java remove possible reason for weird error: NoClassDefFoundError: Could not initialize class org.compiere.util.Trace

(cherry picked from commit 4294608aa65cf25f0d95ab32f6f586c26e3a6224)

Co-authored-by: Tobias Schöneberg <metas-ts@users.noreply.github.com>