Fix the ClassCastException by using recent API calls
...and not assuming a particular queryfilter subtype

ClassCastException: CompositeQueryFilter cannot be cast to SqlQueryFilter https://github.com/metasfresh/metasfresh/issues/1440
(cherry picked from commit c1899c875e97c708b441d8aa0448d43d640de1d7)