#209 start webui server headless
else, it might introduce some jasper issues
see
http://stackoverflow.com/questions/3628302/jasperreports-noclassdeffounderror-exception-on-net-sf-jasperreports-engine-util