Hope this solves the issue. @gp1864 can you confirm?
to verify, i think you need to pull the latest from emtasfresh-parent and mvn install it
Error: Could not find or load main class ${argLine} #3073