Shipment -> Modular Contract Log (Sales) (#16208)
* Prüfauftrag - Fachberater wird nicht angezeigt (#15276)

* Prüfauftrag - Fachberater wird nicht angezeigt
refs: https://github.com/metasfresh/metasfresh/issues/15274

* use ExternalId (#15286)

* remove hazelcast dependency from the shopware6 code (#15294)

- version 3.9-EA is outdated
- we don't need distributed data-structures because we use just one camel container
- instead add geronimo-jcache-simple

(cherry picked from commit 09b0d0e6d91f2622e589855fc8d8571a95aa01c8)

Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>

* Fix the REST-API method to PUT (#15306)

...to be in line with the API's expected method

* People resource reservation on project simulation (#15311)

* HumanResourceTestGroups wip

* prototype

* prototype

* prototype

* further changes

* small refactoring

* human resource score improvements

* small refactoring

* small refactoring

* unit test fix

* QA

---------

Co-authored-by: fp-ps <fp-ps@pevesoft.com>
Co-authored-by: Teo Sarca <teo.sarca@metasfresh.com>
Co-authored-by: dm-ps <dragos.moca@pevesoft.ro>

* compute nextWeekMonday fix (#15313)

* compute nextWeekMonday accordingly

* remove unused imports

---------

Co-authored-by: fp-ps <fp-ps@pevesoft.com>

* fix failing unit test (#15318)

Co-authored-by: fp-ps <fp-ps@pevesoft.com>

* move iron_plant launch configs to custom project

* fix exception to be language-independent

* Fix Calendrer Remaining Translations

* Fix Calendar Remaining Translations

* Fix calendar remaining trl

* Fix calendar remaining trl

* Fix calendar remaining trl

* Display Internal Name Field in advanced edit -> resources window

* Fix calendar remaining trl

* Fix calendar remaining trl

* fix cucumber (#15367)

* Mzorn/ip180 jdk at runtime (#15425)

* basing app runtime images on jdk to fix issue with optaplanner using drools ANC needing jdk

* basing api runtime images on jdk to fix issue with optaplanner using drools ANC needing jdk

* cleanup

* removing dependency dwControl-fonts since we dont need it

* fix unit tests (#15455)

#13861

(cherry picked from commit a2a56589da84a74bff16d46ef77b23c73ad56784)

Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>

* attempt to fix failing cucumber build (#15499)

(cherry picked from commit 2de89b4a98054b0089a6dbca4ceb285045cd6936)
(cherry picked from commit 5ebd02f5f85e71c699281e5e7eed6770b0293a22)

Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>

* move service in abstract class (#15707)

(cherry picked from commit 7ca833bc64e24ecf4f5b15e153d7cdc790b8fbb7)

Co-authored-by: metas_rc <ruxandra.craciunescu@metasfresh.com>

* Start distributing tests a bit (#15544) (#15732)

* attempt to fix failing cucumber build
(cherry picked from commit 2de89b4a98054b0089a6dbca4ceb285045cd6936)

* gh-action cucumber on multiple runners: rename the tags
 also distribute the dozend or so slowest cucumber-tests onto the two additional runners that we now have

(cherry picked from commit 0f8808871694c7f33eac02a4244991c5c9d40c80)
(cherry picked from commit a5584b424911b07a5e8f66d50b3d91cc7950f87f)

Co-authored-by: Tobias Schöneberg <metas-ts@users.noreply.github.com>

* fix unit test that failed if not certain other tests were executed first (#15738) (#15772)

(cherry picked from commit c37193e00b84ba4647515ab8407225d00bc9e98b)

Co-authored-by: Tobias Schöneberg <metas-ts@users.noreply.github.com>

* attempt to improve the logging

* minor log fix

* Improve external-systems-logging (#16030)

* improve the logging
* minor log fix

* propagate simulation dates to `WOTargetStartDate` and `WOTargetEndDate` (#16085)

* initial commit https://github.com/metasfresh/metasfresh/issues/16082

* fix workOrderProjectDataExportAudit.feature

* fix workOrderProjectAPI.feature

---------

Co-authored-by: fp-ps <fp-ps@pevesoft.com>

* skip validation for endDate when startDate is provided (#16101)

Co-authored-by: fp-ps <fp-ps@pevesoft.com>

* fixed merge

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* fix duplicated imports

* Fix swing client in x2go & java-17 (#16232)

* Wrap window.pack for the find dialog into a try-catch

see https://stackoverflow.com/questions/75209745/problems-in-migrating-java-17-from-java-8-with-x2go-terminal-mode

* Remove getUIClassID method - doesn't work because it's not a static field anymore

This gets rid of errors like the following on startup with java-17:

----
17:14:54.193 [main] WARN org.adempiere.plaf.AdempierePLAF - Failed getting the uiClassID of class javax.swing.JComboBox
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.String javax.swing.JComboBox.uiClassID accessible: module java.desktop does not "opens javax.swing" to unnamed module @397fbdb
----

* Regression Tests -> make sure not to many logs are created

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* hotfix M_InOutLine.MovementQty/QtyEntered UOMs bugs

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Fix another window.pack() related error (x2go java17) (#16242)

catch another exception on window.pack()

See https://stackoverflow.com/q/75209745/1012103

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Revert "Merge remote-tracking branch 'origin/iron_plant_uat' into inner_silence_uat_gh16207"

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

* Shipment -> Modular Contract Log (Sales)

---------

Co-authored-by: dm-ps <83770997+dm-ps@users.noreply.github.com>
Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>
Co-authored-by: Tobias Schöneberg <metas-ts@users.noreply.github.com>
Co-authored-by: Manuel Zorn <mpeelen@gmx.de>
Co-authored-by: fp-ps <78536821+fp-ps@users.noreply.github.com>
Co-authored-by: fp-ps <fp-ps@pevesoft.com>
Co-authored-by: Teo Sarca <teo.sarca@metasfresh.com>
Co-authored-by: dm-ps <dragos.moca@pevesoft.ro>
Co-authored-by: mergify[bot] <37929162+mergify[bot]@users.noreply.github.com>
Co-authored-by: metas_rc <ruxandra.craciunescu@metasfresh.com>