remove obsolete stuff that's causing problems
i.e.
java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.joran.conditional.IfAction - Could not find Janino library on the class path. Skipping conditional processing.