Remove getUIClassID method - doesn't work because it's not a static field anymore
This gets rid of errors like the following on startup with java-17:

----
17:14:54.193 [main] WARN org.adempiere.plaf.AdempierePLAF - Failed getting the uiClassID of class javax.swing.JComboBox
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.String javax.swing.JComboBox.uiClassID accessible: module java.desktop does not "opens javax.swing" to unnamed module @397fbdb
----