try to extend bpartner.js with vendorPriceList but broke something
when i run purchase_create_vendor_spec.js I get
cypress_runner.js:161489 TypeError: (intermediate value).vendor(...).vendorPricingSystem is not a function
    at Context.eval (webpack:///./cypress/integration/purchase_create_vendor_spec.js?:20)

when i get purchase_order_spec.js, i get a similar error;
if I comment out
      .vendorPricingSystem("Testpreisliste Lieferanten")
      .vendorDiscountSchema("STandard")
the error doesn't happen