FRESH-658 #370 Double click needed for weighing machine and occasional NPE
TcpConnectionEndpoint:
* better control over what exactly we send, also more logging
* configurable read timeout

ParserException: fix error message
(cherry picked from commit 3f1dfb48d2c8a6684a3d6c7742ccf8e19018328f)