Column R_Request was removed sometime ago. Now also adapting model classes (#17688)
* Column R_Request was removed sometime ago. Now also adapting model classes
* Trace.java remove possible reason for weird error: NoClassDefFoundError: Could not initialize class org.compiere.util.Trace