Inner silence/uat/fix x2go swingui (#16304) (#16311)
* Fix swing client in x2go & java-17 (#16232)

* Wrap window.pack for the find dialog into a try-catch

see https://stackoverflow.com/questions/75209745/problems-in-migrating-java-17-from-java-8-with-x2go-terminal-mode

* Remove getUIClassID method - doesn't work because it's not a static field anymore

This gets rid of errors like the following on startup with java-17:

----
17:14:54.193 [main] WARN org.adempiere.plaf.AdempierePLAF - Failed getting the uiClassID of class javax.swing.JComboBox
java.lang.reflect.InaccessibleObjectException: Unable to make field private static final java.lang.String javax.swing.JComboBox.uiClassID accessible: module java.desktop does not "opens javax.swing" to unnamed module @397fbdb
----

(cherry picked from commit 6c32ec2287db46e8e46f8490362ab94da9b81c9e)

* Fix another window.pack() related error (x2go java17) (#16242)

catch another exception on window.pack()

See https://stackoverflow.com/q/75209745/1012103

(cherry picked from commit a3291f094d8c6509b43db9063540479e26e4c8f3)

* Stop doing find-panels before the actual window is shown (#16250)

See code-comment and https://stackoverflow.com/q/75209745/1012103

(cherry picked from commit da112944f36aa75c0070366a33bff9e1f23e3c5f)
(cherry picked from commit e18ea20e7affccdb172600d105f1f1c21b52bbd9)

Co-authored-by: Tobias Schöneberg <metas-ts@users.noreply.github.com>