FRESH-276: going back to spring boot 1.3.3 after having had
this in the log:
Caused by: java.lang.IllegalStateException:
java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.core.joran.action.NestedBasicPropertyIA -
Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION