hopefully fix the bug
the problem was that the same order line was added by from the C_Order and the C_OrderLine model interceptor

the error looked like this:
org.adempiere.exceptions.AdempiereException: IllegalArgumentException: Multiple entries with same key: OrderLineId(repoId=1003157)=AvailableForSalesResult.Quantities(qtyOnHandStock=0, qtyToBeShipped=40.000) and OrderLineId(repoId=1003157)=AvailableForSalesResult.Quantities(qtyOnHandStock=0, qtyToBeShipped=40.000)