Merge master (#6865)
* Add fixes for dates depending on the locale #6712 (#6715)

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

* Add fixes for dates depending on the locale #6712 (#6715)

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>
(cherry picked from commit c388007feb18de1c5084058a99a544b7c8d8ccf1)

* #6615 comment out credit memo after partial request (#6728)

* Gh6615 4 add process description (#6733)

* Gh6615 5 rename migration file (#6736)

* #6615 comment out credit memo after partial request

https://github.com/metasfresh/metasfresh/issues/6615

* #6615 delete unneeded code and refactoring warning message

https://github.com/metasfresh/metasfresh/issues/6615

* #6615 don't assume anything on this level. The user will make they needed changes.

https://github.com/metasfresh/metasfresh/issues/6615

* #6615 update CreateCreditMemo process description

https://github.com/metasfresh/metasfresh/issues/6615

* #6615 Allow the user to allocate as much as they want on a credit memo

https://github.com/metasfresh/metasfresh/issues/6615

* #6615 Cleanup the code.

* The old partial credit memo handling is no longer needed so we decided to drop it completely, not keep it for docu purposes.
https://github.com/metasfresh/metasfresh/issues/6615

* #6615 update process description

https://github.com/metasfresh/metasfresh/issues/6615

* #6615 rename script

https://github.com/metasfresh/metasfresh/issues/6615

* Gh6743 uom conversion with round UP (#6744)

* when converting quantities, round up

* #6743 repair the tests to fit the new rounding mode

https://github.com/metasfresh/metasfresh/issues/6743

Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>

* #6615 null check in pay selection updater

https://github.com/metasfresh/metasfresh/issues/6615

* #6718 Fix uomconvertdirect.sql and MD_Stock_From_HUs_V.sql (#6755)

(cherry picked from commit 2259f58cd516cd5fcd675c5b7677e8521251fb2f)

* #6718 fix case of missing MD_Stock records

* Window Distribution Order enhancements (#6752)

* Window Distribution Order enhancements
refs: https://github.com/metasfresh/metasfresh/issues/6713

* 6723 table tests (#6773)

* Fix formatting in the config and fixed import #6723

* Reordered the structure for the fixtures #6732

* Test the props passed #6723

* Add test with store data #6723

* Remove debug line  #6723

* Table status update check #6723

* Base TableCell tests #6723

* Skel for TableContextMenu #6723

* Removed comment from #6723

* Added eventsourcemock and settings in jest for the TableContextMenu #6723

* Test if TableContextMenu is rendering properly #6723

* More unit tests added to TableContextMenu #6723

* Add fixture for the EntryTable component #6723

* Added skel for the EntryTable tests #6723

* Small fix to ditch the warnings complaining about required fncts #6723

* Managed to do fixes to the mockup in order to render properly the component #6732

* Fix linter err

* Added fixture for the TableFilter #6723

* Basic tests for rendering TestingFilter #6723

* Fixtures for the TableHeader #6723

* Small fixes in the TableItem #6723

* Add unit tests for the TableHeader #6723

* Prettier formatting #6723

* Fixtures for table pagination

* Base test for TablePagination #6723

* Test active page #6723

* Pagination tests selection #6723

* TablePagination compressed tests #6723

* Added fixtures for the TableQuickInput #6723

* TableQuickInput basic rendering test #6723

* Removed debug

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

* `Payment Allocation` action shall open also when Payments not available (#6776)

* #6777 Shall refresh even if is single document (#6778)

* #6777 Shall refresh even if is single document

* minor: add comments

Co-authored-by: Tobias Schöneberg <metas-ts@users.noreply.github.com>

* #6777 Repair process refresh - invalidate documents (#6781)

* moved to callout (#6748)

https://github.com/metasfresh/metasfresh/issues/6745

* Show scrollbar when exceeds the visible area #6687 (#6775)

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

* Update metasfresh-dist-serverRoot_jrebel.launch

* #6785 don't spread `this.state` when setting state (#6786)

* Master manual invoice (#6787)

* Fix unit tests (#6788)

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

* Better error handling in tabs (#6789)

* #6713 Fixed minor details. (#6793)

* #6794 Changed font size and unbolded it. (#6795)

* gh6784_3_ic (#6792)

* AllocationAmounts.toString() improvements (i.e. make it shorter)

* fix PaymentsViewAllocateCommand.toPayableDocument + tests

https://github.com/metasfresh/metasfresh/issues/6784

* #6779 Now sending 0 instead of null to frontend in the case we receive 0 for the qty to invoice override field. (#6780)

* #6779 Now sending 0 instead of null to frontend in the case we receive 0 for the qty to invoice override field.

* Set the null value when we have no number in the input

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

* Add fixes for dates depending on the locale #6712 (#6715)

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

(cherry picked from commit c388007feb18de1c5084058a99a544b7c8d8ccf1)

* Fix accidental inactivation of not-IBAN bank accounts (#6799)

* Fix accidental inactivation of not-IBAN bank accounts (#6799)

(cherry picked from commit 58f0e4db77c2e77b16e75193adc7494872850558)

* Fix accidental inactivation of not-IBAN bank accounts (#6799)

manually porting the changes from master commit https://github.com/metasfresh/metasfresh/commit/58f0e4db77c2e77b16e75193adc7494872850558

* Wrong Organisation set to HUs when doing Inventory or Material Receipt (#6783)

Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>

* set C_Invoice_Candidate.ApprovalForInvoicing=Y when enqueing for invoicing (#6768)

https://github.com/metasfresh/metasfresh/issues/6767

* set C_Invoice_Candidate.ApprovalForInvoicing=Y when enqueing for invoicing (#6768)

https://github.com/metasfresh/metasfresh/issues/6767

* Gh6769 (#6770)

* payment allocation - book Bank Fee Amount

Gh6769 (#6770)
(cherry picked from commit 7fd422eb7e74f7ab6e05181b69ce01caaa2f68f5)

* payment allocation - book Bank Fee Amount

after-CP fixes; also fixing some javadoc-errors
Gh6769 (#6770)

* Invisible croissant remote excel (#6806)

* change H000 ComsAgreement from 901 to 903

* fixing strange build problem

* Fix date when only one number used (#6809)

* Fix date when only one number used

* Formatting date fix

* unrelated build problem fix

(cherry picked from commit 2efff0685e64b81304e0f17da6d98218cfa0dcde)

* Prettify code

* Add debouncer

* Tune up debouncer

* removed debouncer as it is impacting the other widgets

* Added unit test for the function and removed the export

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>
Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>

* drop old function - avoid error where PG doesn't know which one to pick

* drop old function - avoid error where PG doesn't know which one to pick

* drop old function - avoid error where PG doesn't know which one to pick

* #6779 2nd try - Now able to set 0 to invoice override field on catch weight billing candidates (#6815)

* #6779 Now able to set 0 to invoice override field on catch weight billing candidates.

* #6779 minor comment changes

Co-authored-by: dragospodariu96 <58212697+dragospodariu96@users.noreply.github.com>

* Add date formatting also in the Attributes dropdown (#6816)

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

* Create 5560940_sys_gh6769_trls.sql

https://github.com/metasfresh/metasfresh/issues/6769

* Create 5560941_sys_gh6769_trls.sql

https://github.com/metasfresh/metasfresh/issues/6769

* #6817 Warehouse Temperature and Additional Information fields now in product translation window. (#6818)

* Commission calculation without invoicing (#6813)

Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>

* build fix

* unpost with p_force='Y', see comment

* #6817 Translated Additional Information column and moved organisation last in grid view. (#6825)

* Set locale from the local store (#6824)

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

* Allow wholeTax-taxes also if the document has IsTaxIncluded=N (#6821)

also minor improvements in ITaxBL, MInvoiceTax and IInvoiceCandidateHandlerBL

* use LocalDate instead of java.util.Date (#6830)

* Translation: `Transportation Order` / `Bill of Lading` (#6823)

* introduce PostingError_Issue_ID to all accountable documents (#6820)

* #6803 Can now generate delivery days for a specific tour version. (#6804)

Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>

* Set correctly the date according to locale if the date is updated with the string from BE in iso (#6831)

Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>

* Extend Invoice reversal API to return affected ICs (#6828)

* Update metasfresh-dist-serverRoot_jrebel-ssh_tunnel.launch

* fix after merge

* set guarantor-name as company name to the guarantor-address (#6826)

Goal: have the guarantor on the printed invoice if guarantor != patient

* fix BankStatementPaymentBL.linkSinglePayment (#6835)

https://github.com/metasfresh/metasfresh/issues/6769

* Update InvoiceReferenceNosTest.java

hotfix test

* ProcurementFlatrateHandlerTests: convert to Junit5, avoid Mockit

* refactor and introduced utils/locale.js to get/set current locale (#6837)

* Fix the case where warehouse `Std Warehouse` (`M_Warehouse_ID = 540008`) does not exist. Part 1 (#6832)

Co-authored-by: pvpurcarcosmin <pv.purcar.cosmin@gmail.com>

* disable schedulers (#6840)

https://github.com/metasfresh/metasfresh/issues/5816

* gh6769_4_uat (#6843)

* hotfix BankSatementPaymentBL: create/match payment on TrxAmt instead of StmtAmt
* hotfix avoid using the same payment when we have 2 identical bank statement lines

https://github.com/metasfresh/metasfresh/issues/6769

* test window sandbox (#6836)

* hotfix: when saving AD_Element(s), convert empty ColumnName to null; also did a small cleanup and removed not used code.
* Create 5561270_sys_testWindowSandbox.sql

https://github.com/metasfresh/metasfresh/issues/6845

* #6451 Take out secutiry filter

* Master add metasfresh dev (#6805)

Co-authored-by: TheBestPessimist <cristian@tbp.land>
Co-authored-by: Teo Sarca <teo.sarca@gmail.com>
Co-authored-by: Teo Sarca <t.sarca@metas-fresh.com>
Co-authored-by: Teo Sarca <teo.sarca@metasfresh.com>
Co-authored-by: metas-rc <ruxandra.craciunescu@metasfresh.com>
Co-authored-by: Cristina Ghita <cristina.ghita@metasfresh.com>
Co-authored-by: Cristina <cristinamghita@gmail.com>
Co-authored-by: pvpurcarcosmin <50879041+pvpurcarcosmin@users.noreply.github.com>
Co-authored-by: Julian Bischof <metas-jb@users.noreply.github.com>

* #6451 Fix Functins to get the correct balance

* #6451 FIx name

* Attribute ID shall not be shown in Attribute Editor/ Attribute Button (#6849)

* Create 5561110_sys_gh6819_AD_Issue_IssueCategory_mandatory.sql

https://github.com/metasfresh/metasfresh/issues/6819

* Add sql query to cleanup all ASIs which have description = ASI_ID (#6855)

* #6819 solve SQL error

ERROR: column "issuecategory" contains null values

* #6451 Transform account parameter to search field

* #6860 rearranging_marketing_platform_view (#6861)

* Fix linter error

* Use locale utils where possible

- update tests

* another linter error

Co-authored-by: Petrica Nanca <petrica_nanca@yahoo.com>
Co-authored-by: Petrica Nanca <petrica.nanca@metasfresh.com>
Co-authored-by: Ruxandra Craciunescu <ruxandra.craciunescu@metasfresh.com>
Co-authored-by: Tobias Schöneberg <tobias.schoeneberg@metasfresh.com>
Co-authored-by: pvpurcarcosmin <50879041+pvpurcarcosmin@users.noreply.github.com>
Co-authored-by: TheBestPessimist <cristian@tbp.land>
Co-authored-by: Cristina Ghita <cristina.ghita@metasfresh.com>
Co-authored-by: Tobias Schöneberg <metas-ts@users.noreply.github.com>
Co-authored-by: pvpurcarcosmin <pv.purcar.cosmin@gmail.com>
Co-authored-by: Teo Sarca <teo.sarca@metasfresh.com>
Co-authored-by: dragospodariu96 <58212697+dragospodariu96@users.noreply.github.com>
Co-authored-by: Cristina <cristinamghita@gmail.com>
Co-authored-by: Teo Sarca <teo.sarca@gmail.com>
Co-authored-by: Teo Sarca <t.sarca@metas-fresh.com>
Co-authored-by: Julian Bischof <metas-jb@users.noreply.github.com>
Co-authored-by: Norbert <metasnw@users.noreply.github.com>